[[redirects]]
  from = "/"
  to = "/index.min.html"
  force = true
  status = 200

[[redirects]]
  from = "/games"
  to = "/games.min.html"
  force = true
  status = 200

[[redirects]]
  from = "/web"
  to = "/web.min.html"
  force = true
  status = 200

[[redirects]]
  from = "/changelog"
  to = "/changelog.min.html"
  force = true
  status = 200

[[redirects]]
  from = "/worldmap"
  to = "/worldmap.min.html"
  force = true
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' 'nonce-style'; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'nonce-script'; img-src 'self' data:; child-src 'none'; font-src 'self';"
