[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs.minifierOptions]
    collapseBooleanAttributes = true
    collapseInlineTagWhitespace = true
    collapseWhitespace = true
    conservativeCollapse = true
    decodeEntities = true
    preventAttributesEscaping = true
    processConditionalComments = true
    removeAttributeQuotes = true
    removeComments = true
    removeEmptyAttributes = true
    removeOptionalTags = true
    removeRedundantAttributes = true
