[[redirects]]
  from = "/"
  to = "/index.html"
  force = true
  status = 200

[[redirects]]
  from = "/games"
  to = "/games.html"
  force = true
  status = 200

[[redirects]]
  from = "/web"
  to = "/web.html"
  force = true
  status = 200

[[redirects]]
  from = "/changelog"
  to = "/changelog.html"
  force = true
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' 'nonce-style' fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'nonce-script'; img-src 'self' *.cloudfront.net; child-src 'none'; font-src 'self' fonts.gstatic.com;"

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs.minifierOptions]
    collapseBooleanAttributes = true
    collapseInlineTagWhitespace = true
    collapseWhitespace = true
    conservativeCollapse = true
    decodeEntities = true
    preventAttributesEscaping = true
    processConditionalComments = true
    removeAttributeQuotes = true
    removeComments = true
    removeEmptyAttributes = true
    removeOptionalTags = true
    removeRedundantAttributes = true
